[project]
authors = ["Elia Cereda <eliacereda@gmail.com>"]
channels = ["conda-forge", "Memfault"]
name = "crazyflie-firmware"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13,<3.14"

c-compiler = ">=1.11.0,<2"
make = ">=4.4.1,<5"

# STM32 toolchain
xpack-gcc-arm-none-eabi = ">=13.3.1.1.1,<14"
ncurses = ">=6.5,<7"
coreutils = ">=9.5,<10"
sed = ">=4.9,<5"

[pypi-dependencies]
cfclient = ">=2025.9, <2026"
